import Map from './Map';
import Markers from './Markers';
import InfoWindow from './InfoWindow';
import Graphs from './Graphs';
import Heatmap from './Heatmap';
import Boundary from './Boundary';
import ControlBar from './controls/ControlBar';
import MapType from './controls/MapType';
import OverView from './controls/OverView';
import Scale from './controls/Scale';
import ToolBar from './controls/ToolBar';
import Geolocation from './controls/Geolocation';
import Autocomplete from './Autocomplete';
import MassMarks from './MassMarks';
import ContextMenu from './ContextMenu';
import { getAddress, getLocation, getRegionalCoordinates, getDistance } from './utils/geocoder';
import Track from './Track';

Map.Markers = Markers;
Map.InfoWindow = InfoWindow;
Map.Graphs = Graphs;
Map.Heatmap = Heatmap;
Map.Boundary = Boundary;
Map.ControlBar = ControlBar;
Map.MapType = MapType;
Map.OverView = OverView;
Map.Scale = Scale;
Map.ToolBar = ToolBar;
Map.Geolocation = Geolocation;
Map.Autocomplete = Autocomplete;
Map.MassMarks = MassMarks;
Map.ContextMenu = ContextMenu;
Map.Track = Track;
Map.getAddress = getAddress;
Map.getLocation = getLocation;
Map.getRegionalCoordinates = getRegionalCoordinates;
Map.getDistance = getDistance;

export default Map;
